parameters:
  multi_tenancy:
    tenant_class: App\Entity\Tenant


services:
  _defaults:
    autowire: true
    autoconfigure: true

  Norvutec\MultiTenancyBundle\EventSubscriber\TenantRequestListener:
    arguments: ['@doctrine.orm.default_entity_manager', '@doctrine.dbal.tenant_connection', '%multi_tenancy.tenant_class%']