parameters:
  multi_tenancy:
    tenant_class: App\Entity\Tenant
    tenant_select_route: app_tenant_select
    tenant_migration_config: 'config/migrations/tenant.yaml'


services:
  _defaults:
    autowire: true
    autoconfigure: true

  Norvutec\MultiTenancyBundle\Service\MultiTenancyService:
    arguments: ['@doctrine.orm.default_entity_manager', '@doctrine.dbal.tenant_connection', '%multi_tenancy.tenant_class%']

  Norvutec\MultiTenancyBundle\EventSubscriber\TenantRequestListener:
    arguments: ['@multi_tenancy.service', '@router.default', '%multi_tenancy.tenant_select_route%']

  multi_tenancy.service:
    alias: Norvutec\MultiTenancyBundle\Service\MultiTenancyService

  multi_tenancy.tenant_profiler_collector:
    class: Norvutec\MultiTenancyBundle\DataCollector\TenantProfilerCollector
    public: false
    tags:
      - { name: data_collector, template: '@NorvutecMultiTenancy/tenant_profiler.html.twig' }

#  Norvutec\MultiTenancyBundle\Command\Doctrine\MigrateCommand:
#    arguments: ['@multi_tenancy.service', '%multi_tenancy.tenant_migration_config%']
#  Norvutec\MultiTenancyBundle\Command\Doctrine\DiffCommand:
#    arguments: [ '@multi_tenancy.service', '%multi_tenancy.tenant_migration_config%' ]